version: "3.3"
services:
    vncserver:
        image: dorowu/ubuntu-desktop-lxde-vnc
        ports:
          - 80:80
          - 5090:5090
        environment:
          - VNC_PASSWORD= vncpass
        volumes:
          - type: volume
            source: vncdata
            target: /dev/shm
          - type: bind
            source: /root
            target: /mnt

volumes:
    vncdata: